baseURL = "http://localhost"

# 网站标题
title   = "Life-Long Learning"
description = "Here is a collection of my notes."
author = "Rustle Karl"

# 摘要长度
summaryLength = 5

# 语言
languageCode = "en-us"

# 主题
theme = "hello-friend"

# 分页数量
paginate  = 10

# 文件目录
archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true


# ======== 评论 ========
[params.valine]
	enable = true
    appId = 'Lh1YFw4l6DiggQrfu6aiCN7X-gzGzoHsz'
    appKey = 'NkEgd3s2fNmceT0q1oFI9tnS'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true
# ======== 评论 ========

# ======== 添加修改时间 ========
enableGitInfo   = false  # 用 Docker 则必须关闭
[frontmatter]
    lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
# ======== 添加修改时间 ========

enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = true
disable404     = false
disableHugoGeneratorInject = false
useRelativeCover = true

# ======== 搜索 ========
[params.algolia]
  appId = "V484EHT8P4"
  indexName = "notes"
  searchOnlyKey = "4977360d5e70c48256a6f11534b05780"

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true
# ======== 搜索 ========

[permalinks]
  posts = "/posts/:year/:month/:day/:title/"

[taxonomies]
  tag      = "tags"  # 文章标签
  category = "categories"  # 文章分类
  series   = "series"  # 文章主题/文章系列

[params]
  # 主页默认显示的类别
  contentTypeName = "archive"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # Show reading time in minutes for posts
  showReadingTime = true
  MinuteReadingTime = "minutes read"

  # 显示自动生成的目录
  toc = true
  autoCollapseToc = true   # 自动展开目录

  # 是否开启看板娘
  live2D = true

  [params.logo]
    logoText     = "# ls /root/"
    logoHomeLink = "/"

[languages]
  [languages.en]
    keywords = ""
    weight    = 1
    menuMore = "more"
    writtenBy = ""
    readOtherPosts = "Read Other Posts"

    # 修改时间样式
    lastModDisplay = "updated:"

    dateFormatSingle = "2006.01.02"
    dateFormatList = "2006.01.02"

[menu]
  [[menu.main]]
    identifier = "series"
    name       = "series"
    url        = "/series/"
    weight = 14

  [[menu.main]]
    identifier = "tags"
    name       = "tags"
    url        = "/tags/"
    weight = 12

  [[menu.main]]
    identifier = "archive"
    name       = "archive"
    url        = "/archive/"
    weight = 10

  [[menu.main]]
    identifier = "example"
    name       = "example"
    url        = "/example/"
    weight = 18

  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "music"
    name       = "music"
    url        = "/music/"
